#! /usr/bin/env bash

source "${HOMEgefs:-${HOMEgfs}}/ush/preamble.sh"

####################################
# Determine Job Output Name on System
####################################
export jobid=${jobid:-"${job}.${PBS_JOBID}"}
export pgmout="OUTPUT.${PBS_JOBID}"
export pgmerr=errfile

####################################
# Specify and create working directory
####################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

######################################
# Set up compute resources
######################################
export total_tasks=${total_tasks:-4}
#export APRUN_MPMD=${gefsmpexec_mpmd:-"mpiexec -n $total_tasks cfp mpmd_cmdfile"}
export APRUN_MPMD=${gefsmpexec_mpmd:-"mpiexec --cpu-bind core --configfile mpmd_cmdfile"}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gefs}
export envir=${envir:-prod}
export RUN=${RUN:-gefs}

######################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# SENDECF  - Flag Events on ECF
# VERBOSE  - Specify Verbose Output
######################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export VERBOSE=${VERBOSE:-YES}

######################################
# Set up the date information
######################################
export cycle=t${cyc}z
setpdy.sh
source PDY

if [ ${FORECAST_SEGMENT:-hr} = lr ]; then
  export cyc=00
  export cycle=t${cyc}z
fi

####################################
# Specify Execution Areas
####################################
export HOMEgefs=${HOMEgefs:-${PACKAGEROOT}/gefs.${gefs_ver}}
export PARMgefs=${PARMgefs:-${HOMEgefs}/parm}
export EXECgefs=${EXECgefs:-${HOMEgefs}/exec}
export USHgefs=${USHgefs:-${HOMEgefs}/ush}

#############################
# Source relevant config files
#############################
#export CDATE=$PDY$cyc
configs="base prdgen"
config_path=${PARMgefs}/config
for config in ${configs}; do
  . ${config_path}/config.${config}
  export err=$?
  if [[ $err != 0 ]]; then
    echo "FATAL ERROR in ${BASH_SOURCE[0]}: Error while loading parm file ${config_path}/config.${config}"
    exit $err
  fi
done

##############################################
# Define COM directories
##############################################
ver=${gefs_ver:0:5}
export ROTDIR=${ROTDIR:-$(compath.py ${envir}/com/${NET}/${ver})}
export ROTDIR_GFS=${ROTDIR_GFS:-$(compath.py ${envir}/com/gfs/${gfs_ver})}

if [[ $cplchm = ".true." ]]; then
    COMPONENT="chem"
fi

export COMPONENT=${COMPONENT:-atmos}

echo "Environment before calling script"
env | sort

# Construct COM variables from templates (see config.com)

declare -rx memchar=${RUNMEM}

MEMDIR="${memchar}" YMD=${PDY} HH=${cyc} generate_com -rx COM_ATMOS_HISTORY COM_ATMOS_MASTER

export PRDGEN_STREAMS="res_2p50 res_0p50 res_0p25_s1 res_0p25_s2"

if [[ ${RUNMEM} == "memgfs" ]]; then
  grids="2p50 0p25 0p25s 0p50a 0p50b"
elif [[ ${RUNMEM} == "memaer" ]]; then
  grids="0p25 0p25s 0p50a 0p50b"
else
  if [ ${FORECAST_SEGMENT} = lr ]; then
    grids="2p50 0p50a 0p50b"
  else
    grids="2p50 0p25 0p25s 0p50a 0p50b"
  fi
fi

for grid in ${grids}; do
  prod_dir="COM_ATMOS_GRIB_${grid}"
  MEMDIR="${memchar}" GRID=${grid} YMD=${PDY} HH=${cyc} generate_com -rx "${prod_dir}:COM_ATMOS_GRIB_TMPL"
  if [[ ! -d "${prod_dir}" ]]; then mkdir -m 775 -p "${!prod_dir}"; fi
done

#############################################################
# Execute the script
#source $HOMEgefs/scripts/exgefs_atmos_prdgen.sh
export err=$?
if [[ $err == 0 ]]; then
  echo "${job} completed normally!"
else
  echo "FATAL ERROR in ${BASH_SOURCE[0]}: ${job} failed!"
  exit ${err}
fi
#############################################################

##############################
# Remove the Temporary working directory
##############################
cd ${DATAROOT}
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf ${DATA} ; fi

exit $err
